version: 2

sources:
  - name: gw_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: "Products data table"
      - name: sales
        identifier: raw_gz_sales
        description: "Sales data table"
      - name: ship
        identifier: raw_gz_ship
        description: 	"Shipping data table"
